/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_svmp_stream_Session */

#ifndef _Included_org_mitre_svmp_stream_Session
#define _Included_org_mitre_svmp_stream_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mitre_svmp_stream_Session
 * Method:    InitSockClient
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_stream_Session_InitSockClient
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_svmp_stream_Session
 * Method:    SockClientWrite
 * Signature: (ILorg/mitre/svmp/stream/RTSPEventMessage;)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_stream_Session_SockClientWrite
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_mitre_svmp_stream_Session
 * Method:    SockClientClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mitre_svmp_stream_Session_SockClientClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
